//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClientss.NilaiServices1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NilaiInfo", Namespace="http://schemas.datacontract.org/2004/07/ServerWCF")]
    [System.SerializableAttribute()]
    public partial class NilaiInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeteranganField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodeKelasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KodePelajaranField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NISField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Nilai_HarianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Nilai_UASField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Nilai_UTSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Rata_rataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TahunAjaranField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keterangan {
            get {
                return this.KeteranganField;
            }
            set {
                if ((object.ReferenceEquals(this.KeteranganField, value) != true)) {
                    this.KeteranganField = value;
                    this.RaisePropertyChanged("Keterangan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodeKelas {
            get {
                return this.KodeKelasField;
            }
            set {
                if ((object.ReferenceEquals(this.KodeKelasField, value) != true)) {
                    this.KodeKelasField = value;
                    this.RaisePropertyChanged("KodeKelas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KodePelajaran {
            get {
                return this.KodePelajaranField;
            }
            set {
                if ((object.ReferenceEquals(this.KodePelajaranField, value) != true)) {
                    this.KodePelajaranField = value;
                    this.RaisePropertyChanged("KodePelajaran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NIS {
            get {
                return this.NISField;
            }
            set {
                if ((this.NISField.Equals(value) != true)) {
                    this.NISField = value;
                    this.RaisePropertyChanged("NIS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nilai_Harian {
            get {
                return this.Nilai_HarianField;
            }
            set {
                if ((this.Nilai_HarianField.Equals(value) != true)) {
                    this.Nilai_HarianField = value;
                    this.RaisePropertyChanged("Nilai_Harian");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nilai_UAS {
            get {
                return this.Nilai_UASField;
            }
            set {
                if ((this.Nilai_UASField.Equals(value) != true)) {
                    this.Nilai_UASField = value;
                    this.RaisePropertyChanged("Nilai_UAS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nilai_UTS {
            get {
                return this.Nilai_UTSField;
            }
            set {
                if ((this.Nilai_UTSField.Equals(value) != true)) {
                    this.Nilai_UTSField = value;
                    this.RaisePropertyChanged("Nilai_UTS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Passwords {
            get {
                return this.PasswordsField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordsField, value) != true)) {
                    this.PasswordsField = value;
                    this.RaisePropertyChanged("Passwords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rata_rata {
            get {
                return this.Rata_rataField;
            }
            set {
                if ((this.Rata_rataField.Equals(value) != true)) {
                    this.Rata_rataField = value;
                    this.RaisePropertyChanged("Rata_rata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TahunAjaran {
            get {
                return this.TahunAjaranField;
            }
            set {
                if ((object.ReferenceEquals(this.TahunAjaranField, value) != true)) {
                    this.TahunAjaranField = value;
                    this.RaisePropertyChanged("TahunAjaran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NilaiServices1.INilai")]
    public interface INilai {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INilai/getNilai", ReplyAction="http://tempuri.org/INilai/getNilaiResponse")]
        WCFClientss.NilaiServices1.NilaiInfo[] getNilai();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INilai/getNilai", ReplyAction="http://tempuri.org/INilai/getNilaiResponse")]
        System.Threading.Tasks.Task<WCFClientss.NilaiServices1.NilaiInfo[]> getNilaiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INilai/getNilaiByID", ReplyAction="http://tempuri.org/INilai/getNilaiByIDResponse")]
        WCFClientss.NilaiServices1.NilaiInfo[] getNilaiByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INilai/getNilaiByID", ReplyAction="http://tempuri.org/INilai/getNilaiByIDResponse")]
        System.Threading.Tasks.Task<WCFClientss.NilaiServices1.NilaiInfo[]> getNilaiByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INilai/insertNilai", ReplyAction="http://tempuri.org/INilai/insertNilaiResponse")]
        int insertNilai(WCFClientss.NilaiServices1.NilaiInfo data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INilai/insertNilai", ReplyAction="http://tempuri.org/INilai/insertNilaiResponse")]
        System.Threading.Tasks.Task<int> insertNilaiAsync(WCFClientss.NilaiServices1.NilaiInfo data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INilai/updateNilai", ReplyAction="http://tempuri.org/INilai/updateNilaiResponse")]
        int updateNilai(WCFClientss.NilaiServices1.NilaiInfo data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INilai/updateNilai", ReplyAction="http://tempuri.org/INilai/updateNilaiResponse")]
        System.Threading.Tasks.Task<int> updateNilaiAsync(WCFClientss.NilaiServices1.NilaiInfo data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INilai/GantiPass", ReplyAction="http://tempuri.org/INilai/GantiPassResponse")]
        int GantiPass(WCFClientss.NilaiServices1.NilaiInfo data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INilai/GantiPass", ReplyAction="http://tempuri.org/INilai/GantiPassResponse")]
        System.Threading.Tasks.Task<int> GantiPassAsync(WCFClientss.NilaiServices1.NilaiInfo data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INilaiChannel : WCFClientss.NilaiServices1.INilai, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NilaiClient : System.ServiceModel.ClientBase<WCFClientss.NilaiServices1.INilai>, WCFClientss.NilaiServices1.INilai {
        
        public NilaiClient() {
        }
        
        public NilaiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NilaiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NilaiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NilaiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFClientss.NilaiServices1.NilaiInfo[] getNilai() {
            return base.Channel.getNilai();
        }
        
        public System.Threading.Tasks.Task<WCFClientss.NilaiServices1.NilaiInfo[]> getNilaiAsync() {
            return base.Channel.getNilaiAsync();
        }
        
        public WCFClientss.NilaiServices1.NilaiInfo[] getNilaiByID(string id) {
            return base.Channel.getNilaiByID(id);
        }
        
        public System.Threading.Tasks.Task<WCFClientss.NilaiServices1.NilaiInfo[]> getNilaiByIDAsync(string id) {
            return base.Channel.getNilaiByIDAsync(id);
        }
        
        public int insertNilai(WCFClientss.NilaiServices1.NilaiInfo data) {
            return base.Channel.insertNilai(data);
        }
        
        public System.Threading.Tasks.Task<int> insertNilaiAsync(WCFClientss.NilaiServices1.NilaiInfo data) {
            return base.Channel.insertNilaiAsync(data);
        }
        
        public int updateNilai(WCFClientss.NilaiServices1.NilaiInfo data) {
            return base.Channel.updateNilai(data);
        }
        
        public System.Threading.Tasks.Task<int> updateNilaiAsync(WCFClientss.NilaiServices1.NilaiInfo data) {
            return base.Channel.updateNilaiAsync(data);
        }
        
        public int GantiPass(WCFClientss.NilaiServices1.NilaiInfo data) {
            return base.Channel.GantiPass(data);
        }
        
        public System.Threading.Tasks.Task<int> GantiPassAsync(WCFClientss.NilaiServices1.NilaiInfo data) {
            return base.Channel.GantiPassAsync(data);
        }
    }
}
